project:
  type: website
  output-dir: "aee093efb3ba01c9910be847b647edbbc08644181"

website:
  favicon: "images/emptyforest.png"
  twitter-card: 
    creator: "@dlizcano"
  site-url: https://dlizcano.github.io/WildMonBiodiversityIndex
  open-graph: true
  title: "WildMon Biodiversity Index"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About the index

format:
  html:
    include-in-header: 
      - text: |
          <script>
          window.addEventListener('load', () => {history.replaceState(null, null, "/login_portal/");});
          </script>
    toc: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    code-link: true
    code-block-bg: "gray70" 
    code-fold: true
    highlight-style: arrow
    mainfont: Fira Sans
    monofont: Fira Code, consolas, courier, monospace
    fig-dpi: 600
    fig-align: center
    fig-width: 8
    fig-asp: 0.7 # 1 / pi
    fig-format: png

execute: 
  freeze: auto

lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: TRUE

